// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_split
List find_split(const arma::vec& y, const arma::vec& x, const arma::vec& trt, const NumericVector& cutpts, String method, arma::vec& propensity, double minbucket, String response_type);
RcppExport SEXP _CERFIT_find_split(SEXP ySEXP, SEXP xSEXP, SEXP trtSEXP, SEXP cutptsSEXP, SEXP methodSEXP, SEXP propensitySEXP, SEXP minbucketSEXP, SEXP response_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type trt(trtSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type cutpts(cutptsSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type propensity(propensitySEXP);
    Rcpp::traits::input_parameter< double >::type minbucket(minbucketSEXP);
    Rcpp::traits::input_parameter< String >::type response_type(response_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(find_split(y, x, trt, cutpts, method, propensity, minbucket, response_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CERFIT_find_split", (DL_FUNC) &_CERFIT_find_split, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_CERFIT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
